/* Static leadership demonstration. All records are illustrative and stored locally only. */
const SOURCE=window.AAHI_DEMO;
const STORE='avicenna-oab-demo-v1';
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>{if(!d)return 'Not scheduled';const [y,m,day]=d.split('-').map(Number);return new Date(y,m-1,day).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});};
let saved={};try{saved=JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){}
let state={program:SOURCE.programs[saved.program]?saved.program:'MAC',view:'overview',recs:clone(SOURCE.programs),addedEvidence:Array.isArray(saved.addedEvidence)?saved.addedEvidence:[],search:'',filter:'all',detail:null};
if(saved.recs&&typeof saved.recs==='object')for(const key of Object.keys(SOURCE.programs)){
 if(Array.isArray(saved.recs[key]))state.recs[key].recs=saved.recs[key];
}
const titles={overview:'Occupational Advisory Board Review Center',membership:'Board Membership',meetings:'Meeting Workspace',program:'Program Review',outcomes:'Outcomes',tracker:'Recommendation Tracker',evidence:'Evidence Library'};
const $=s=>document.querySelector(s);
function persist(){try{localStorage.setItem(STORE,JSON.stringify({program:state.program,recs:Object.fromEntries(Object.entries(state.recs).map(([k,v])=>[k,v.recs])),addedEvidence:state.addedEvidence}))}catch(e){toast('Browser storage is unavailable. Changes may not persist.')}}
function info(){return state.recs[state.program]}
function statusClass(s){return s.toLowerCase().replace(/\s+/g,'-')}
function status(s){return `<span class="status ${statusClass(s)}">${esc(s)}</span>`}
function pill(s,cl=''){return `<span class="pill ${cl}">${esc(s)}</span>`}
function recs(){return info().recs}
function missing(){return recs().filter(r=>r.evidenceStatus==='Missing'||r.evidenceStatus==='Planned')}
function metrics(){const r=recs();return {all:r.length,progress:r.filter(x=>x.status==='In Progress').length,decision:r.filter(x=>x.status==='Awaiting Decision').length,gaps:missing().length}}
function evidenceState(r){const linked=state.addedEvidence.some(e=>e.program===state.program&&e.rec===r.id);return linked?'Link added (demo)':r.evidenceStatus}
function statusOptions(sel){return ['Not Started','Planned','Awaiting Decision','In Progress','Completed','Deferred'].map(s=>`<option ${sel===s?'selected':''}>${s}</option>`).join('')}
function toast(t){let el=document.createElement('div');el.className='toast';el.textContent=t;document.body.appendChild(el);setTimeout(()=>el.remove(),2800)}
function navigate(view){state.view=view;state.search='';state.filter='all';history.replaceState(null,'','#'+view);render();window.scrollTo({top:0,behavior:'instant'});$('#sidebar').classList.remove('open')}
function top(){ $('#pageTitle').textContent=titles[state.view]; $('#programSelect').value=state.program;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));}
function head(label,h,sub,actions=''){return `<div class="page-head"><div><div class="tiny-eyebrow">${label}</div><h2>${h}</h2><p>${sub}</p></div>${actions?`<div class="page-actions">${actions}</div>`:''}</div>`}
function kpis(){const m=metrics();return `<div class="metric-grid">
<div class="metric"><div class="metric-label">RECOMMENDATIONS LOGGED</div><div class="metric-number">${m.all}</div><div class="metric-sub">Illustrative items · selected board</div></div>
<div class="metric orange"><div class="metric-label">IN PROGRESS</div><div class="metric-number">${m.progress}</div><div class="metric-sub">Assigned to program owners</div></div>
<div class="metric red"><div class="metric-label">AWAITING DECISION</div><div class="metric-number">${m.decision}</div><div class="metric-sub">Requires documented response</div></div>
<div class="metric blue"><div class="metric-label">EVIDENCE GAPS</div><div class="metric-number">${m.gaps}</div><div class="metric-sub">Missing or planned documents</div></div>
</div>`}
function table(rows){return `<div class="panel flush"><div class="table-wrap"><table><thead><tr><th>Recommendation / feedback</th><th>Owner</th><th>Due date</th><th>Status</th><th>Evidence</th><th>Decision trail</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td style="min-width:240px"><div class="row-title">${esc(r.text)}</div><div class="row-sub">${esc(r.id)} · ${esc(r.category)} · ${fmt(r.date)}</div></td><td>${esc(r.owner)}</td><td>${fmt(r.due)}</td><td>${status(r.status)}</td><td>${pill(evidenceState(r),evidenceState(r).includes('Missing')?'orange':'teal')}</td><td><button class="inline-link" data-detail="${esc(r.id)}">View trail ↗</button></td></tr>`).join(''):`<tr><td colspan="6"><div class="empty-state">No recommendations match your filters.</div></td></tr>`}</tbody></table></div></div>`}
function overview(){let p=info();return head('PROGRAM ADVISORY REVIEW',esc(p.name),'A single view of employer feedback, institutional decisions and evidence of resulting action.',`<button class="btn btn-teal" data-action="add">+ Add sample item</button>`)+kpis()+`<div class="section">${head('DECISION TRACKING','Recommendations and Actions','Select any recommendation to follow the full employer-feedback → decision → action → evidence pathway.',`<button class="btn btn-outline" data-view-go="tracker">Open full tracker →</button>`)}</div>`+table(recs())+`<div class="section grid-two"><div class="panel"><div class="side-title">How a recommendation closes the loop ${pill('Illustrative flow','teal')}</div><div class="timeline"><div class="timeline-step"><h4>01 · Employer feedback</h4><p>Board members describe an occupational need and the meeting record captures the recommendation.</p></div><div class="timeline-step"><h4>02 · AAHI decision</h4><p>The institution records its decision, rationale, assigned owner and target date.</p></div><div class="timeline-step"><h4>03 · Action taken</h4><p>A curriculum, competency, equipment or clinical workflow change is documented.</p></div><div class="timeline-step"><h4>04 · Evidence of completion</h4><p>The revised material and relevant minutes are linked for review.</p></div></div></div><div class="panel"><div class="side-title">Program review focus</div><div class="review-grid">${p.review.slice(0,4).map(x=>`<div class="review-item"><span class="pill">${esc(x[2])}</span><h4>${esc(x[0])}</h4><p>${esc(x[1])}</p></div>`).join('')}</div><button class="btn btn-soft" data-view-go="program" style="margin-top:16px">View all review areas →</button></div></div>`}
function tracker(){let rows=recs().filter(r=>(state.filter==='all'||r.status===state.filter)&&(!state.search||[r.id,r.text,r.category,r.owner,r.decision].join(' ').toLowerCase().includes(state.search.toLowerCase())));return head('RECOMMENDATION TRACKING','Recommendations and Actions','Trace each item from advisor input to a decision, implementation and supporting evidence.',`<button class="btn btn-outline" data-action="export">Export CSV</button><button class="btn btn-teal" data-action="add">+ Add sample item</button>`)+kpis()+`<div class="section"><div class="filters"><input id="search" aria-label="Search recommendations" placeholder="Search item, owner or keyword…" value="${esc(state.search)}"><select id="filter" aria-label="Filter by status"><option value="all">All statuses</option>${['Not Started','Planned','Awaiting Decision','In Progress','Completed','Deferred'].map(s=>`<option ${state.filter===s?'selected':''}>${s}</option>`).join('')}</select></div>${table(rows)}</div>`}
function membership(){return head('COMMITTEE STRUCTURE',esc(info().name)+' Board Membership','Sample board-seat layout; no actual member identities or contact details appear in this public prototype.')+`<div class="info-strip"><strong>Staff-only information:</strong> Names, employers, term dates, phone numbers and email addresses must remain in an authenticated staff system, not in this public static demo.</div><div class="section grid-three">${[['External Seat 01','Industry employer advisor','Employer / occupational role: to be verified'],['External Seat 02','Industry employer advisor','Employer / occupational role: to be verified'],['External Seat 03','Industry employer advisor','Employer / occupational role: to be verified'],['AAHI Liaison','Internal program representative','Coordinates agenda, responses and evidence'],['Recording Support','Internal administrative role','Documents attendance and minutes'],['Additional Advisors','Optional as appropriate','Confirm representation by applicable service area']].map((x,i)=>`<div class="action-card"><div class="tiny-eyebrow">${esc(x[0])} ${pill('Sample seat')}</div><h4>${esc(x[1])}</h4><p>${esc(x[2])}</p><div style="margin-top:14px">${pill(i<3?'External representation':'Internal role',i<3?'teal':'')}</div></div>`).join('')}</div><div class="section panel"><h3>Membership record fields for a secured version</h3><div class="review-grid">${['Member and employer','Occupational role and expertise','Service-area representation','Appointment/term dates','Meeting attendance','Staff-only contact details'].map(t=>`<div class="review-item">${esc(t)}</div>`).join('')}</div></div>`}
function meetings(){return head('MEETING WORKSPACE',esc(info().name)+' Committee Meetings','A single meeting record should connect agenda, attendance, minutes, recommendations and follow-up.',`<button class="btn btn-soft" data-view-go="evidence">Evidence library →</button>`)+`<div class="grid-two"><div class="panel"><div class="tiny-eyebrow">ILLUSTRATIVE UPCOMING MEETING</div><h3 style="font-size:22px;margin-top:7px">${fmt(info().next)}</h3><p class="side-meta">Houston — Main Campus · face-to-face planning example · location/time not yet recorded</p><div class="section-head section"><h3>Draft agenda</h3>${pill('Not approved','orange')}</div><ol class="meeting-agenda"><li>Call to order, introductions, occupational representation</li><li>Review of prior recommendations and AAHI responses</li><li>Program curriculum, practical skills and equipment review</li><li>Completion, credential and placement discussion (dated data)</li><li>New employer recommendations, owners and dates</li><li>Next actions and confirmation of follow-up</li></ol></div><div class="panel"><h3>Documentation checkpoints</h3><div class="review-grid">${[['Agenda','Draft / not uploaded'],['Attendance','Not documented'],['Minutes','Not documented'],['Prior recommendations','Sample tracker available'],['Signed supporting items','Not documented'],['Program review','Preview checklist available']].map(x=>`<div class="review-item"><div class="tiny-eyebrow">${esc(x[0])}</div><p style="margin-top:7px">${esc(x[1])}</p></div>`).join('')}</div><div class="info-strip" style="margin-top:16px">A sample meeting date or checklist is not evidence a real meeting occurred. Attach dated records to a secured version before using this for accreditation review.</div></div></div><div class="section panel"><div class="side-title">Prior board activity <span class="pill orange">Illustrative only</span></div><p class="side-meta">Sample prior review date: ${fmt(info().previous)}. Employer recommendations appear in the tracker; actual minutes and attendance have not been supplied.</p><button class="btn btn-outline" data-view-go="tracker" style="margin-top:13px">Review sample recommendations</button></div>`}
function programReview(){return head('PROGRAM REVIEW',esc(info().name)+' Review Matrix',esc(info().focus))+`<div class="grid-two"><div class="panel"><h3>Review areas</h3><div class="review-grid">${info().review.map(([t,d,s])=>`<div class="review-item"><span class="pill">${esc(s)}</span><h4>${esc(t)}</h4><p>${esc(d)}</p></div>`).join('')}</div></div><div class="panel"><h3>Employer verification discussion</h3><div class="timeline"><div class="timeline-step"><h4>Relevance</h4><p>Are the occupational tasks and knowledge current for local entry-level work?</p></div><div class="timeline-step"><h4>Resources and experience</h4><p>Do students practice with suitable equipment, software or workplace processes?</p></div><div class="timeline-step"><h4>Graduate preparation</h4><p>What do employer advisors identify as strengths and gaps in expected readiness?</p></div><div class="timeline-step"><h4>Institutional response</h4><p>Which recommendations become approved changes, and how are they documented?</p></div></div><div class="info-strip">This is a planning matrix, not a completed accreditation review or official committee determination.</div></div></div>`}
function outcomes(){let a=info().outcomes;return head('OUTCOMES REVIEW',esc(info().name)+' Outcomes','A demonstration of how completion, credential, placement and employer feedback could be presented with an explicit reporting period.')+`<div class="info-strip"><strong>SAMPLE VALUES ONLY — NOT AAHI PERFORMANCE DATA.</strong> Replace with verified figures, numerator, denominator, cohort definition, methodology and reporting period before institutional use.</div><div class="section outcome-grid">${[['Completion',a.completion],['Credential / certification',a.credential],['Placement',a.placement],['Positive employer feedback',a.feedback]].map(([l,v])=>`<div class="outcome"><div class="label">${esc(l)}</div><div class="value">${v}%</div><div class="progress-track"><div class="progress-fill" style="width:${v}%"></div></div><div class="row-sub">${esc(info().period)}</div></div>`).join('')}</div><div class="section panel"><h3>Illustrative comparison</h3>${[['Completion',a.completion],['Credential / certification',a.credential],['Placement',a.placement],['Employer feedback',a.feedback]].map(([l,v])=>`<div class="bar-row"><strong>${esc(l)}</strong><div class="bar-bg"><span style="width:${v}%"></span></div><strong>${v}%</strong></div>`).join('')}</div><div class="section empty-state"><strong>Production requirements:</strong> show reporting period, cohort/population, denominator and source; record approval/version; distinguish collected results from committee interpretation. Nothing on this page should be treated as a published performance report.</div>`}
function evidence(){let links=state.addedEvidence.filter(e=>e.program===state.program);return head('EVIDENCE LIBRARY','Evidence & Document Register','Track the document needed to substantiate each committee step. Links entered in the demo remain only in this browser.',`<button class="btn btn-teal" data-action="add-evidence">+ Add demo link</button>`)+`<div class="info-strip"><strong>Storage limitation:</strong> this prototype records only example metadata/links in your browser. It does not upload files, verify signatures, restrict access or preserve an institutional audit trail.</div><div class="section evidence-list">${[['Agenda','Dated agenda for each committee meeting','Not uploaded'],['Attendance','Physical and virtual attendance plus occupational representation','Not uploaded'],['Minutes','Typed minutes capturing activity, recommendations and attendance','Not uploaded'],['Survey / employer feedback','Dated feedback and review responses','Not uploaded'],['Decision log','Institutional decision and owner for each recommendation','Illustrative tracker'],['Revised documents','Curriculum, checklist or equipment evidence','Not uploaded']].map(x=>`<div class="evidence-tile"><div><strong>${esc(x[0])}</strong><small>${esc(x[1])}</small></div>${pill(x[2],x[2]==='Not uploaded'?'orange':'teal')}</div>`).join('')}</div><div class="section"><div class="section-head"><div><h3>Recommendation-linked evidence</h3><p>Shows which sample records would need supporting files.</p></div></div><div class="panel flush"><div class="table-wrap"><table><thead><tr><th>ID</th><th>Expected evidence</th><th>Record state</th></tr></thead><tbody>${recs().map(r=>`<tr><td>${esc(r.id)}</td><td>${esc(r.evidence)}</td><td>${pill(evidenceState(r),evidenceState(r)==='Missing'?'orange':'teal')}</td></tr>`).join('')}</tbody></table></div></div></div><div class="section"><div class="section-head"><div><h3>Links added in this browser</h3><p>Demonstration metadata; not a controlled document repository.</p></div></div>${links.length?`<div class="evidence-list">${links.map((e,i)=>`<div class="evidence-tile"><div><strong>${esc(e.title)}</strong><small>${esc(e.rec)} · ${esc(e.type)} · ${fmt(e.date)}</small></div><a class="btn btn-outline btn-sm" href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">Open ↗</a></div>`).join('')}</div>`:`<div class="empty-state">No sample evidence links have been entered. Use “Add demo link” to show how a document register would work.</div>`}</div>`}
function insights(){let p=info();let m=missing();$('#insights').innerHTML=`<div class="panel"><div class="side-title">Next Committee Meeting ${pill('Sample')}</div><div class="tiny-eyebrow">${esc(p.abbr)} ADVISORY BOARD</div><div class="side-date">${fmt(p.next)}</div><div class="side-meta">Houston — Main Campus<br>Time and room: not entered<br>Meeting mode: proposed face-to-face example</div><button class="btn btn-soft" data-view-go="meetings" style="margin-top:14px;width:100%">Open meeting workspace ↗</button></div><div class="panel"><div class="side-title">Missing Evidence <span class="status awaiting-decision">${m.length} items</span></div><ul class="side-list">${m.slice(0,4).map(r=>`<li><span class="alert-icon">!</span><div><strong>${esc(r.id)}</strong><div class="side-meta">${esc(r.evidence)} · ${esc(r.evidenceStatus)}</div></div></li>`).join('')}</ul>${m.length>4?`<div class="row-sub">+ ${m.length-4} more evidence items</div>`:''}<button class="btn btn-outline" data-view-go="evidence" style="margin-top:13px;width:100%">View evidence register</button></div><div class="panel"><div class="side-title">Review readiness</div><div class="side-note"><strong>Board-level traceability</strong><br>Employer feedback → AAHI decision → assigned action → supporting document.</div><div class="side-note" style="margin-top:9px"><strong>Before real-world use</strong><br>Validate workflow and required fields against the COE handbook applicable to AAHI's accreditation stage.</div><a href="https://council.org/maintaining-accrediation/" target="_blank" rel="noopener noreferrer" class="inline-link" style="display:inline-block;margin-top:13px">COE maintenance guidance ↗</a></div>`}
function render(){top();let f={overview,membership,meetings,program:programReview,outcomes,tracker,evidence}[state.view]||overview;$('#content').innerHTML=f();insights();bind()}
function findRec(id){return recs().find(x=>x.id===id)}
function modal(t,html,actions=''){const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop" role="presentation"><div class="modal" role="dialog" aria-modal="true" aria-label="${esc(t)}"><div class="modal-header"><h2>${esc(t)}</h2><button class="modal-close" aria-label="Close dialog">×</button></div><div class="modal-body">${html}</div>${actions?`<div class="modal-actions">${actions}</div>`:''}</div></div>`;root.querySelector('.modal-close').onclick=close;root.querySelector('.modal-backdrop').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))close()});}
function close(){$('#modalRoot').innerHTML=''}
function detail(id){let r=findRec(id);if(!r)return;modal(`${r.id} · Recommendation trail`,`<div>${status(r.status)} ${pill(r.category)} ${pill('Illustrative')}</div><h3 style="line-height:1.45">${esc(r.text)}</h3><div class="grid-two"><div class="note-block"><strong>Owner</strong>${esc(r.owner)}<div class="row-sub">Target: ${fmt(r.due)}</div></div><div class="note-block"><strong>Meeting source</strong>${fmt(r.date)}<div class="row-sub">Illustrative committee meeting</div></div></div><div class="timeline"><div class="timeline-step"><h4>01 · Employer feedback</h4><div class="date">${fmt(r.date)}</div><p>${esc(r.history?.[0]||r.text)}</p></div><div class="timeline-step"><h4>02 · AAHI decision</h4><p>${esc(r.decision||'Decision pending.')}</p></div><div class="timeline-step"><h4>03 · Assigned action</h4><p>${esc(r.action||'Not entered.')}</p></div><div class="timeline-step"><h4>04 · Evidence / verification</h4><p>${esc(r.evidence)} — ${esc(evidenceState(r))}. ${r.evidenceStatus==='Sample only'?'Sample completion text does not replace actual dated evidence.':''}</p></div></div><div class="info-strip">Changes here affect only your browser's copy of this illustrative dashboard. They are not official institutional actions.</div><div class="section"><h3>Edit sample decision</h3><div class="form-grid"><div class="field"><label>Status</label><select id="editStatus">${statusOptions(r.status)}</select></div><div class="field"><label>Target date</label><input type="date" id="editDue" value="${esc(r.due)}"></div><div class="field wide"><label>AAHI decision</label><textarea id="editDecision">${esc(r.decision)}</textarea></div><div class="field wide"><label>Action / implementation note</label><textarea id="editAction">${esc(r.action)}</textarea></div></div></div>`,`<button class="btn" id="cancelModal">Cancel</button><button class="btn btn-teal" id="saveRec">Save demo changes</button>`);
$('#cancelModal').onclick=close;$('#saveRec').onclick=()=>{r.status=$('#editStatus').value;r.due=$('#editDue').value;r.decision=$('#editDecision').value.trim();r.action=$('#editAction').value.trim();persist();close();render();toast('Illustrative record updated in this browser.')};}
function addRec(){modal('Add sample recommendation',`<div class="info-strip" style="margin-bottom:16px">Add a fictional item to demonstrate the workflow. Do not enter actual member information or confidential records.</div><div class="form-grid"><div class="field wide"><label>Recommendation *</label><textarea id="newText" maxlength="500" placeholder="Describe the employer recommendation"></textarea></div><div class="field"><label>Category</label><input id="newCat" value="Curriculum" maxlength="60"></div><div class="field"><label>Owner (role only)</label><input id="newOwner" value="Program Director" maxlength="70"></div><div class="field"><label>Meeting date</label><input type="date" id="newDate" value="${info().previous}"></div><div class="field"><label>Due date</label><input type="date" id="newDue" value="${info().next}"></div><div class="field wide"><label>Expected evidence</label><input id="newEvidence" value="Revised document / approval record" maxlength="140"></div></div>`,`<button class="btn" id="cancelModal">Cancel</button><button class="btn btn-teal" id="createRec">Add sample item</button>`);$('#cancelModal').onclick=close;$('#createRec').onclick=()=>{let t=$('#newText').value.trim();if(!t){toast('Enter a sample recommendation.');return}let prefix=state.program==='DENTAL'?'DAC':state.program;let ids=recs().map(x=>Number(x.id.split('-')[1])||0);let id=prefix+'-'+String(Math.max(0,...ids)+1).padStart(2,'0');recs().push({id,date:$('#newDate').value,category:$('#newCat').value.trim()||'Curriculum',text:t,owner:$('#newOwner').value.trim()||'Program Director',due:$('#newDue').value,status:'Awaiting Decision',decision:'Pending institutional decision.',action:'Not yet assigned.',evidence:$('#newEvidence').value.trim()||'Supporting documentation',evidenceStatus:'Missing'});persist();close();render();toast('Sample recommendation added.');};}
function addEvidence(){modal('Add demo evidence link',`<div class="info-strip" style="margin-bottom:16px">This stores link metadata locally in your browser only. It is not file upload or a secure institutional archive.</div><div class="form-grid"><div class="field wide"><label>Document title *</label><input id="evTitle" maxlength="140" placeholder="e.g., EKG rubric draft"></div><div class="field"><label>Recommendation</label><select id="evRec">${recs().map(r=>`<option value="${esc(r.id)}">${esc(r.id)}</option>`).join('')}</select></div><div class="field"><label>Document type</label><select id="evType"><option>Revised curriculum</option><option>Skills checklist</option><option>Minutes</option><option>Attendance</option><option>Agenda</option><option>Equipment documentation</option><option>Other evidence</option></select></div><div class="field"><label>Document date</label><input type="date" id="evDate" value="2026-09-24"></div><div class="field wide"><label>Public/sample HTTPS link *</label><input type="url" id="evUrl" placeholder="https://example.org/sample.pdf"></div></div>`,`<button class="btn" id="cancelModal">Cancel</button><button class="btn btn-teal" id="saveEvidence">Add demo link</button>`);$('#cancelModal').onclick=close;$('#saveEvidence').onclick=()=>{let title=$('#evTitle').value.trim(),url=$('#evUrl').value.trim();if(!title){toast('Enter a document title.');return}try{let u=new URL(url);if(u.protocol!=='https:')throw Error('https');}catch(e){toast('Enter a valid HTTPS link.');return}state.addedEvidence.push({program:state.program,title,rec:$('#evRec').value,type:$('#evType').value,date:$('#evDate').value,url});persist();close();render();toast('Demo evidence link added locally.');};}
function csvCell(v){let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
function exportCSV(){let fields=['ID','Program','Meeting date','Category','Recommendation','Owner role','Due date','Status','Decision','Action','Expected evidence','Evidence status'];let rows=recs().map(r=>[r.id,info().name,r.date,r.category,r.text,r.owner,r.due,r.status,r.decision,r.action,r.evidence,evidenceState(r)]);let csv='\ufeff'+[fields,...rows].map(a=>a.map(csvCell).join(',')).join('\r\n');let u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));let a=document.createElement('a');a.href=u;a.download='Avicenna-'+state.program+'-ILLUSTRATIVE-recommendations.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function bind(){document.querySelectorAll('[data-view-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.viewGo));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='add')addRec();if(b.dataset.action==='export')exportCSV();if(b.dataset.action==='add-evidence')addEvidence()});let search=$('#search'),filter=$('#filter');if(search)search.oninput=e=>{state.search=e.target.value;let start=search.selectionStart;$('#content').innerHTML=tracker();bind();let n=$('#search');n.focus();n.setSelectionRange(start,start)};if(filter)filter.onchange=e=>{state.filter=e.target.value;$('#content').innerHTML=tracker();bind()}}
for(let [k,v]of Object.entries(SOURCE.programs)){let opt=document.createElement('option');opt.value=k;opt.textContent=v.name;$('#programSelect').appendChild(opt)}
$('#programSelect').onchange=e=>{state.program=e.target.value;state.search='';state.filter='all';persist();render()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');
$('#resetDemo').onclick=()=>{if(confirm('Reset all illustrative recommendations and evidence links saved in this browser?')){localStorage.removeItem(STORE);location.reload()}};
$('#printBrief').onclick=()=>{navigate('overview');setTimeout(()=>window.print(),80)};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#modalRoot').firstChild)close()});
let view=location.hash.slice(1);if(titles[view])state.view=view;render();
