/* ALL ITEMS IN THIS FILE ARE ILLUSTRATIVE SAMPLE DATA, NOT AAHI RECORDS. */
window.AAHI_DEMO={
  campuses:["Houston — Main Campus"],
  programs:{
    MAC:{name:"Medical Assisting",abbr:"MAC",board:"Medical Assisting Occupational Advisory Committee",next:"2026-10-22",previous:"2026-09-10",focus:"Clinical procedures, entry-level competency, employer expectations and externship readiness",period:"Illustrative 2026 reporting period",outcomes:{completion:78,credential:72,placement:81,feedback:88},review:[
      ["Curriculum alignment","Review clinical and administrative course sequence","Under review"],["Skills checklists","Cross-check blood pressure, EKG and phlebotomy competencies","Action identified"],["Externship experiences","Compare site feedback to entry-level expectations","Under review"],["Equipment","Inventory EKG and patient-monitoring practice equipment","Action identified"],["Certification readiness","Review exam blueprint alignment and practice questions","Scheduled"],["Proposed changes","Consider updated simulation practice sequence","Under review"]],
      recs:[
        {id:"MAC-01",date:"2026-09-10",category:"Skills checklist",text:"Add a documented EKG lead-placement skill check before externship.",owner:"Program Director",due:"2026-11-06",status:"In Progress",decision:"Approved for pilot in the next instructional cycle.",action:"Draft new rubric, pilot during lab, collect faculty feedback.",evidence:"Revised EKG skills rubric",evidenceStatus:"Missing",meeting:"Illustrative September advisory review",history:["Employer input: entry-level hires need consistent lead-placement practice.","AAHI decision: pilot a pre-externship EKG competency.","Planned action: validate checklist and add faculty sign-off."]},
        {id:"MAC-02",date:"2026-09-10",category:"Equipment",text:"Evaluate whether the available training EKG equipment supports realistic practice.",owner:"Lab Coordinator",due:"2026-10-30",status:"Awaiting Decision",decision:"Pending cost and inventory review.",action:"Compare inventory with skill requirements and prepare options.",evidence:"Equipment inventory and review",evidenceStatus:"Missing",meeting:"Illustrative September advisory review",history:["Employer input: maintain exposure to commonly used EKG workflows.","AAHI decision: pending equipment review."]},
        {id:"MAC-03",date:"2026-09-10",category:"Externship",text:"Use a structured employer feedback form at the close of clinical placement.",owner:"Externship Coordinator",due:"2026-11-20",status:"Planned",decision:"Proposed for next review cycle.",action:"Draft short feedback form tied to skill outcomes.",evidence:"Employer feedback template",evidenceStatus:"Planned",meeting:"Illustrative September advisory review",history:["Employer input: collect consistent performance feedback.","AAHI decision: form under consideration."]},
        {id:"MAC-04",date:"2026-09-10",category:"Curriculum",text:"Align patient-identification scenarios with laboratory competency practice.",owner:"Lead Faculty",due:"2026-10-09",status:"Completed",decision:"Approved as an instructional enhancement.",action:"Updated sample lesson and instructor guide (illustrative).",evidence:"Revised scenario guide",evidenceStatus:"Sample only",meeting:"Illustrative September advisory review",history:["Employer input: reinforce two-identifier workflow.","AAHI decision: approved enhancement.","Illustrative closure: sample lesson updated; evidence still must be verified."]},
        {id:"MAC-05",date:"2026-09-10",category:"Certification",text:"Compare practice questions against the applicable certification content outline.",owner:"Assessment Lead",due:"2026-11-13",status:"In Progress",decision:"Approved for curriculum mapping.",action:"Map existing questions and identify topic gaps.",evidence:"Exam content alignment matrix",evidenceStatus:"Missing",meeting:"Illustrative September advisory review",history:["Employer input: review assessment readiness.","AAHI decision: conduct content mapping."]},
        {id:"MAC-06",date:"2026-09-10",category:"Equipment",text:"Review supplies for repeated blood-pressure and vital-signs practice.",owner:"Lab Coordinator",due:"2026-11-20",status:"Awaiting Decision",decision:"Pending resource planning.",action:"Produce consumables and equipment estimate.",evidence:"Supply estimate",evidenceStatus:"Planned",meeting:"Illustrative September advisory review",history:["Employer input: more repeated practice opportunities.","AAHI decision: pending budget review."]},
        {id:"MAC-07",date:"2026-09-10",category:"Curriculum",text:"Add a short clinical handoff communication exercise to the patient-care module.",owner:"Lead Faculty",due:"2026-11-27",status:"Completed",decision:"Approved for concept demonstration.",action:"Created illustrative activity outline.",evidence:"Handoff activity outline",evidenceStatus:"Sample only",meeting:"Illustrative September advisory review",history:["Employer input: concise handoffs matter for new hires.","AAHI decision: concept included in prototype."]}
      ]},
    DENTAL:{name:"Dental Assisting",abbr:"Dental",board:"Dental Assisting Occupational Advisory Committee",next:"2026-10-29",previous:"2026-09-17",focus:"Chairside preparation, infection control, instruments, imaging safety and clinical readiness",period:"Illustrative 2026 reporting period",outcomes:{completion:75,credential:70,placement:79,feedback:85},review:[
      ["Curriculum alignment","Verify chairside sequence and common workflows","Under review"],["Skills checklists","Assess four-handed dentistry and operatory setup","Action identified"],["Clinical experiences","Compare clinic feedback and student readiness","Scheduled"],["Equipment","Review sterilization and radiography practice resources","Action identified"],["Certification readiness","Review relevant exam preparation","Scheduled"],["Proposed changes","Add operatory turnover simulation","Under review"]],
      recs:[
        {id:"DAC-01",date:"2026-09-17",category:"Skills checklist",text:"Add an operatory turnover checklist that includes clean/dirty zones.",owner:"Program Director",due:"2026-11-13",status:"In Progress",decision:"Approved for checklist pilot.",action:"Draft sequence and faculty validation steps.",evidence:"Operatory turnover checklist",evidenceStatus:"Missing"},
        {id:"DAC-02",date:"2026-09-17",category:"Equipment",text:"Review the sterilization instrument flow demonstrated in lab.",owner:"Lab Coordinator",due:"2026-11-20",status:"Awaiting Decision",decision:"Pending review.",action:"Audit demonstration equipment.",evidence:"Sterilization workflow audit",evidenceStatus:"Missing"},
        {id:"DAC-03",date:"2026-09-17",category:"Clinical",text:"Collect site feedback on chairside readiness at placement close.",owner:"Externship Coordinator",due:"2026-12-04",status:"Planned",decision:"Proposed.",action:"Draft employer survey items.",evidence:"Employer form",evidenceStatus:"Planned"},
        {id:"DAC-04",date:"2026-09-17",category:"Curriculum",text:"Update instrument identification practice for restorative procedures.",owner:"Lead Faculty",due:"2026-10-23",status:"Completed",decision:"Approved for sample curriculum revision.",action:"Sample practice cards drafted.",evidence:"Instrument practice cards",evidenceStatus:"Sample only"},
        {id:"DAC-05",date:"2026-09-17",category:"Safety",text:"Include a radiography safety decision scenario.",owner:"Lead Faculty",due:"2026-11-27",status:"In Progress",decision:"Approved for concept testing.",action:"Draft branching scenario.",evidence:"Scenario draft",evidenceStatus:"Missing"}
      ]},
    MBC:{name:"Medical Billing & Coding",abbr:"MBC",board:"Medical Billing & Coding Occupational Advisory Committee",next:"2026-11-05",previous:"2026-09-24",focus:"Documentation accuracy, coding workflows, claim processing, payer changes and revenue-cycle readiness",period:"Illustrative 2026 reporting period",outcomes:{completion:82,credential:69,placement:76,feedback:84},review:[
      ["Curriculum alignment","Review ICD-10-CM and CPT/HCPCS coverage","Under review"],["Skills checklists","Review claim editing and denial resolution","Action identified"],["Applied experiences","Check encounter-to-claim practice activities","Scheduled"],["Equipment/software","Review coding platform practice needs","Action identified"],["Certification readiness","Review applicable blueprint alignment","Under review"],["Proposed changes","Add more denial management cases","Under review"]],
      recs:[
        {id:"MBC-01",date:"2026-09-24",category:"Coding",text:"Add documentation-driven coding practice with an audit trail.",owner:"Lead Faculty",due:"2026-11-20",status:"In Progress",decision:"Pilot proposed.",action:"Build sample chart-to-code case.",evidence:"Coding case rubric",evidenceStatus:"Missing"},
        {id:"MBC-02",date:"2026-09-24",category:"Claims",text:"Develop simulated denials for medical-necessity review.",owner:"Program Director",due:"2026-12-04",status:"Awaiting Decision",decision:"Pending scope approval.",action:"Define denial categories.",evidence:"Denial case plan",evidenceStatus:"Missing"},
        {id:"MBC-03",date:"2026-09-24",category:"Software",text:"Review access to a claim-entry practice interface.",owner:"Operations Lead",due:"2026-12-11",status:"Planned",decision:"Proposed.",action:"Compare demo platforms.",evidence:"Platform comparison",evidenceStatus:"Planned"},
        {id:"MBC-04",date:"2026-09-24",category:"Curriculum",text:"Include claim correction documentation in applied exercises.",owner:"Lead Faculty",due:"2026-11-06",status:"Completed",decision:"Approved for concept revision.",action:"Illustrative applied exercise updated.",evidence:"Exercise revision",evidenceStatus:"Sample only"}
      ]},
    BHT:{name:"Behavioral Health Technician",abbr:"BHT",board:"Behavioral Health Technician Occupational Advisory Committee",next:"2026-11-12",previous:"2026-09-24",focus:"Therapeutic communication, behavioral observation, crisis prevention, safety and objective documentation",period:"Illustrative 2026 reporting period",outcomes:{completion:80,credential:73,placement:77,feedback:87},review:[
      ["Curriculum alignment","Review therapeutic communication sequence","Under review"],["Skills checklists","Assess observation and documentation practice","Action identified"],["Applied experiences","Review supervision and feedback models","Scheduled"],["Equipment/resources","Review role-play and safety learning materials","Scheduled"],["Certification readiness","Review program-aligned assessment blueprint","Under review"],["Proposed changes","Increase branching de-escalation scenarios","Action identified"]],
      recs:[
        {id:"BHT-01",date:"2026-09-24",category:"Communication",text:"Add a branching scenario for early signs of escalation.",owner:"Lead Faculty",due:"2026-11-13",status:"In Progress",decision:"Approved for demo development.",action:"Draft client dialogue pathways.",evidence:"Scenario script",evidenceStatus:"Missing"},
        {id:"BHT-02",date:"2026-09-24",category:"Documentation",text:"Use an objective versus subjective documentation exercise.",owner:"Program Director",due:"2026-11-20",status:"Awaiting Decision",decision:"Pending content review.",action:"Map common documentation errors.",evidence:"Documentation rubric",evidenceStatus:"Missing"},
        {id:"BHT-03",date:"2026-09-24",category:"Safety",text:"Reinforce response and escalation according to site protocol.",owner:"Lead Faculty",due:"2026-12-04",status:"Planned",decision:"Proposed.",action:"Draft policy-grounded case.",evidence:"Safety case",evidenceStatus:"Planned"},
        {id:"BHT-04",date:"2026-09-24",category:"Boundaries",text:"Add professional-boundary decisions to role-play activities.",owner:"Lead Faculty",due:"2026-11-06",status:"Completed",decision:"Approved for concept enhancement.",action:"Sample role-play outline prepared.",evidence:"Role-play outline",evidenceStatus:"Sample only"}
      ]}
  }
};
